repos:

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/HunterMcGushion/docstr_coverage
    rev: v2.2.0
    hooks:
      - id: docstr-coverage
        args: ["code_dir", "-v", "0", "-F", "0", "-p", "-b", "./badge.svg"]