coverage:
  range: 70..90  # First number represents red, and second represents green
  round: up       # up, down, or nearest
  precision: 2    # Number of decimal places, between 0 and 5

fixes:
  - "/home/runner/work/setup_testing/code/::"

ignore:
  - "setup.py"
  - "*/tests/.*"
  - "__init__.py"
  - "tests/*.py"