repos:

  - repo: https://github.com/HunterMcGushion/docstr_coverage
    rev: v2.2.0
    hooks:
      - id: docstr-coverage
        args: ["--verbose", "2"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black