name: ci-tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install pytest
        run: pip install pytest

      - name: Test requirements installation
        run: python setup.py install

      - name: Prepare test data
        run: |
          unzip tests/data_for_test

      - name: Run unit tests
        run: pytest tests/*.py
