name: ci-tests

on:
  pull_request:

jobs:
  test:

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pytest
        run: pip install pytest

      - name: Test requirements installation
        run: python setup.py install

      - name: Prepare test data
        run: 7z x tests/data_for_test/acdc_for_test.7z

      - name: Run unit tests
        run: pytest tests/*.py

      - name: Codecov uploader
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v3