name: ci-tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  codecov:
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    name: Codecov Workflow
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - id: setup_python
        uses: actions/setup-python@master
        with:
          python-version: '3.8'

      - id: cache-modules
        uses: actions/cache@v3
        with:
          path: ./.venv/
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install reqs
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          python -m venv ./.venv
          . ./.venv/bin/activate
          python setup.py install

      - name: Running tests
        run: |
          . ./.venv/bin/activate
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}




