name: ci-tests

on:
  push:
    branches:
      - "test"
  pull_request:
    branches:
      - "main"

jobs:
  codecov:

    strategy:
      matrix:
        os: [ windows-latest ]

    name: Codecov Workflow
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: Code style fixing
        run: |
          pip install black
          black --target-version=py310 .

      - name: Test requirements installation
        run: python setup.py install

      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: Run unit tests
        run: |
          7z x tests/acdc_for_test.7z
          pytest tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests