name: ci-tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  codecov:

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    name: Codecov Workflow
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip' 
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install pytest pytest-cov bandit sphinx recommonmark
          python -m pip install --upgrade pip
          pip install .




