name: ci-tests

on:
  push:
    branches:
      - "test"
  pull_request:
    branches:
      - "main"

jobs:
  codecov:

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    name: Codecov Workflow
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: Generate docs coverage report
        run: |
          pip install docstr-coverage
          docstr-coverage ./ -b ./badge.svg -p