name: ci-tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  codecov:
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    name: Codecov Workflow
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'
          cache: 'pip'
        uses: actions/cache@master
        id: cache-modules
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install reqs
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          python setup.py install

      - name: Running tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests




