name: ci-tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  ci:
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
          python-version: ["3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}
      py: ${{ matrix.python-version }}
      tmp: 

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
        if: ${{github.ref != 'refs/head/main'}}

      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pre-commit/action@v3.0.0

      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip wheel
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Get pip cache
        id: cached-modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.cached-modules.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt
          pip install black black[jupyter]
          pip install pytest pytest-cov

      - name: Running tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: Os and python version
        if: runner.os == 'Linux'
        run: |
          echo "os: $OS, py-ver: $py"

      - name: Upload coverage to Codecov
        if:  runner.os == 'Linux' && ${{ matrix.python-version }} == 3.8
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: pytest
          fail_ci_if_error: true




