name: ci-tests

on:
  push:
    branches:
      - "test"
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  codecov:

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    name: Codecov Workflow
    runs-on: ${{ matrix.os }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: Code style checking
        run: |
          pip install black
          black --target-version=py39 .

      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov
          7z x tests/data_for_test/acdc_for_test.7z
          coverage run -m pytest --cov=tests/ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
