name: codecov_workflow

on:
  pull_request:

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@master
      - name: Codecov prepare
      - uses: codecov/codecov-action@v3
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

      - name: Codecov config
        with:
          files: ./ci-tests.yml
