name: workflow

on: [push]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'

    steps:
    - uses: actions/checkout@v3
    - name: Install pytest
      run: pip install pytest

    - name: Test requirements installation
      working-directory: setup_testing
      run: |
        pwd
        python setup.py install

    - name: Prepare test data
      working-directory: setup_testing
      run: 7z x tests/data_for_test/acdc_for_test.7z

    - name: Run unit tests
      working-directory: setup_testing
      run: pytest tests/*.py

    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)